spring.application.name=demo-park-api


#=========================================
#LOCALE - configurando o local do sistema
#=========================================

spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

#=====================================
#MySql - configuração do banco de dados
#=====================================

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://SEU_BANCO?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=America/Sao_Paulo
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA

#=======================================
#              JPA
#=======================================

spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

# a configuração abaixo serve para que o hibernate crie as tabelas de acordo com as anotações como @Entity
spring.jpa.hibernate.ddl-auto=update






